### ISSUE TITLE
SSOProviderInvalidToken: the SSO session has expired or is invalid

### ISSUE THREAD

**Issue by sPaCeMoNk3yIam** [aws/lightsailctl#26]
I'm using the modern recommended SSO auth to work with the AWS CLI. `Get`ting resources works well, but the commands that work via this plugin always return an error and try to seem to look for a wrong sso cache file:
 ```
profile "default" is configured to use SSO but is missing required configuration: sso_region, sso_start_url

Command '['lightsailctl', '--plugin', '--input-stdin']' returned non-zero exit status 1.
```

After unnecessarily adding these two parameters to my profile, I still get:
```
SSOProviderInvalidToken: the SSO session has expired or is invalid
caused by: open /Users/<USER>/.aws/sso/cache/<ID>.json: no such file or directory

Command '['lightsailctl', '--plugin', '--input-stdin']' returned non-zero exit status 1.
```
The CLI tries to read from a wrong JSON file.

**Comment by paxan** [comment]
@sPaCeMoNk3yIam 

I think moving `lightsailctl` to AWS SDK for Go v2 (from v1) might resolve this issue. Some cursory look into source of both SDKs tells me that SDK v1 only supports legacy SSO config style, while v2 supports both.

I've made a branch `move-to-aws-sdk-go-v2`. Can you please try getting `lightsailctl` built from this branch?

```
go install github.com/aws/lightsailctl@move-to-aws-sdk-go-v2
```

Resulting binary, `~/go/bin/lightsailctl`, should have this version:

```
~/go/bin/lightsailctl --version
v1.0.6-fix26
```

Make sure this new binary is in your `PATH`.

If you want to undo, and get the currently released binary, just run this command:

```
go install github.com/aws/lightsailctl@latest
```

**Comment by paxan** [comment]
Yep v1 of Go SDK doesn't support this SSO config: <https://github.com/aws/aws-sdk-go/issues/4649>

**Comment by sPaCeMoNk3yIam** [comment]
> @sPaCeMoNk3yIam
> 
> I think moving `lightsailctl` to AWS SDK for Go v2 (from v1) might resolve this issue. Some cursory look into source of both SDKs tells me that SDK v1 only supports legacy SSO config style, while v2 supports both.
> 
> I've made a branch `move-to-aws-sdk-go-v2`. Can you please try getting `lightsailctl` built from this branch, to see if it recognizes your SSO configuration?
> 
> ```
> go install github.com/aws/lightsailctl@move-to-aws-sdk-go-v2
> ```
> 
> Resulting binary, `~/go/bin/lightsailctl`, should have this version:
> 
> ```
> ~/go/bin/lightsailctl --version
> v1.0.6-fix26
> ```
> 
> Make sure this new binary is in your `PATH`.
> 
> If you want to undo, and get the currently released binary, just run this command:
> 
> ```
> go install github.com/aws/lightsailctl@latest
> ```

It seems to not have worked for me:
Using `aws lightsail get-container-images` I get a proper response.
Using `aws lightsail push-container-image` I continue getting
```
operation error Lightsail: CreateContainerServiceRegistryLogin, https response error StatusCode: 400, RequestID: XXX, api error ExpiredTokenException: The security token included in the request is expired

Command '['lightsailctl', '--plugin', '--input-stdin']' returned non-zero exit status 1.

```

**Comment by sPaCeMoNk3yIam** [comment]
@paxan Is there a released for this (rather important) patch planned any time soon?

**Comment by paxan** [comment]
Done: <https://github.com/aws/lightsailctl/releases/tag/v1.0.6>

**Comment by joshuataylor** [comment]
https://docs.aws.amazon.com/lightsail/latest/userguide/amazon-lightsail-install-software.html#install-lightsailctl-on-linux version here is still 1.0.4, not 1.0.6.
